// PLEASE SEE ANSHUL KUMAR'S COMPLETED ASSIGNMENT AT https://github.com/readcreate/mod6assignmentV2.git
// RIGHT NOW YOU'RE LOOKING AT THE FIRST ATTEMPT, WHICH ENDED UP BAD.
// I TRIED THE ASSIGNMENT AGAIN IN A NEW REPOSITORY (LINK ABOVE)
